name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ---- BACKEND ----
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend deps
        working-directory: backend
        run: npm install

      - name: Run backend tests
        working-directory: backend
        run: npm test || echo "No backend tests found"

      # ---- FRONTEND ----
      - name: Install frontend deps
        working-directory: frontend
        run: npm install

      - name: Run frontend tests
        working-directory: frontend
        run: npm run test -- --watch=false --browsers=ChromeHeadless || echo "No frontend tests found"

      - name: Build Angular
        working-directory: frontend
        run: npm run build --prod

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---- Backend ----
      - name: Build and Push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/empleados-backend:latest

      # ---- Frontend ----
      - name: Build and Push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/empleados-frontend:latest
